/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	netboxv1beta1 "github.com/digitalocean/netbox-ip-controller/api/netbox/v1beta1"
	versioned "github.com/digitalocean/netbox-ip-controller/client/clientset/versioned"
	internalinterfaces "github.com/digitalocean/netbox-ip-controller/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/digitalocean/netbox-ip-controller/client/listers/netbox/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetBoxIPInformer provides access to a shared informer and lister for
// NetBoxIPs.
type NetBoxIPInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.NetBoxIPLister
}

type netBoxIPInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNetBoxIPInformer constructs a new informer for NetBoxIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetBoxIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetBoxIPInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNetBoxIPInformer constructs a new informer for NetBoxIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetBoxIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetboxV1beta1().NetBoxIPs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetboxV1beta1().NetBoxIPs(namespace).Watch(context.TODO(), options)
			},
		},
		&netboxv1beta1.NetBoxIP{},
		resyncPeriod,
		indexers,
	)
}

func (f *netBoxIPInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetBoxIPInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *netBoxIPInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&netboxv1beta1.NetBoxIP{}, f.defaultInformer)
}

func (f *netBoxIPInformer) Lister() v1beta1.NetBoxIPLister {
	return v1beta1.NewNetBoxIPLister(f.Informer().GetIndexer())
}
