/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	netboxv1beta1 "github.com/digitalocean/netbox-ip-controller/api/netbox/v1beta1"
	scheme "github.com/digitalocean/netbox-ip-controller/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetBoxIPsGetter has a method to return a NetBoxIPInterface.
// A group's client should implement this interface.
type NetBoxIPsGetter interface {
	NetBoxIPs(namespace string) NetBoxIPInterface
}

// NetBoxIPInterface has methods to work with NetBoxIP resources.
type NetBoxIPInterface interface {
	Create(ctx context.Context, netBoxIP *netboxv1beta1.NetBoxIP, opts v1.CreateOptions) (*netboxv1beta1.NetBoxIP, error)
	Update(ctx context.Context, netBoxIP *netboxv1beta1.NetBoxIP, opts v1.UpdateOptions) (*netboxv1beta1.NetBoxIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netboxv1beta1.NetBoxIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*netboxv1beta1.NetBoxIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netboxv1beta1.NetBoxIP, err error)
	NetBoxIPExpansion
}

// netBoxIPs implements NetBoxIPInterface
type netBoxIPs struct {
	*gentype.ClientWithList[*netboxv1beta1.NetBoxIP, *netboxv1beta1.NetBoxIPList]
}

// newNetBoxIPs returns a NetBoxIPs
func newNetBoxIPs(c *NetboxV1beta1Client, namespace string) *netBoxIPs {
	return &netBoxIPs{
		gentype.NewClientWithList[*netboxv1beta1.NetBoxIP, *netboxv1beta1.NetBoxIPList](
			"netboxips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netboxv1beta1.NetBoxIP { return &netboxv1beta1.NetBoxIP{} },
			func() *netboxv1beta1.NetBoxIPList { return &netboxv1beta1.NetBoxIPList{} },
		),
	}
}
