/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/digitalocean/netbox-ip-controller/api/netbox/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetBoxIPs implements NetBoxIPInterface
type FakeNetBoxIPs struct {
	Fake *FakeNetboxV1beta1
	ns   string
}

var netboxipsResource = schema.GroupVersionResource{Group: "netbox", Version: "v1beta1", Resource: "netboxips"}

var netboxipsKind = schema.GroupVersionKind{Group: "netbox", Version: "v1beta1", Kind: "NetBoxIP"}

// Get takes name of the netBoxIP, and returns the corresponding netBoxIP object, and an error if there is any.
func (c *FakeNetBoxIPs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetBoxIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(netboxipsResource, c.ns, name), &v1beta1.NetBoxIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetBoxIP), err
}

// List takes label and field selectors, and returns the list of NetBoxIPs that match those selectors.
func (c *FakeNetBoxIPs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetBoxIPList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(netboxipsResource, netboxipsKind, c.ns, opts), &v1beta1.NetBoxIPList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NetBoxIPList{ListMeta: obj.(*v1beta1.NetBoxIPList).ListMeta}
	for _, item := range obj.(*v1beta1.NetBoxIPList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested netBoxIPs.
func (c *FakeNetBoxIPs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(netboxipsResource, c.ns, opts))

}

// Create takes the representation of a netBoxIP and creates it.  Returns the server's representation of the netBoxIP, and an error, if there is any.
func (c *FakeNetBoxIPs) Create(ctx context.Context, netBoxIP *v1beta1.NetBoxIP, opts v1.CreateOptions) (result *v1beta1.NetBoxIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(netboxipsResource, c.ns, netBoxIP), &v1beta1.NetBoxIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetBoxIP), err
}

// Update takes the representation of a netBoxIP and updates it. Returns the server's representation of the netBoxIP, and an error, if there is any.
func (c *FakeNetBoxIPs) Update(ctx context.Context, netBoxIP *v1beta1.NetBoxIP, opts v1.UpdateOptions) (result *v1beta1.NetBoxIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(netboxipsResource, c.ns, netBoxIP), &v1beta1.NetBoxIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetBoxIP), err
}

// Delete takes name of the netBoxIP and deletes it. Returns an error if one occurs.
func (c *FakeNetBoxIPs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(netboxipsResource, c.ns, name, opts), &v1beta1.NetBoxIP{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetBoxIPs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(netboxipsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NetBoxIPList{})
	return err
}

// Patch applies the patch and returns the patched netBoxIP.
func (c *FakeNetBoxIPs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetBoxIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(netboxipsResource, c.ns, name, pt, data, subresources...), &v1beta1.NetBoxIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetBoxIP), err
}
