name: Integration test

on:
  pull_request:
    branches:
      - main

jobs:

  integration_test:
    name: Integration test
    strategy:
      matrix:
        go-version: [1.22.3]
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Checkout current branch
      uses: actions/checkout@v4.1.6
      with:
        fetch-depth: '0'

    - name: Get testenv image tag 
      run : |
        export TEST_IMAGE="$(make get-envtest-image-tag -s)"
        echo "TEST_IMAGE=${TEST_IMAGE}" >> ${GITHUB_ENV}
        
    - name: Log in to the Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }} 
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # Build a new testenv image to use if and only if the Dockerfile or Makefile is changed in this PR
    - name: Build image
      run : ./scripts/build-image-conditionally.sh

    - name: Run integration tests
      run : ./scripts/integration-test.sh