name: Integration test

on:
  pull_request:
    branches:
      - master

jobs:

  integration_test:
    name: Integration test
    strategy:
      matrix:
        go-version: [1.18.2]
        platform: [Linux]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Run integration tests
      run : ./scripts/integration-test.sh