name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  go_test:
    name: Test
    strategy:
      matrix:
        go-version: [1.18.2]
        platform: [Linux]

    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Test    
      run: ./.github/workflows/scripts/test.sh
